### ISSUE TITLE
...

### ISSUE THREAD

**Issue by weizhaoji** [XiangLinPro/IT_book#1]

**Comment by XiangLinPro** [comment]
密码很好获取的&nbsp; 公众号【五角钱的程序员】&nbsp; 回复【书籍解压】，即可获取，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiangLinPro/IT_book"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 下午3:55
收件人:&nbsp;"XiangLinPro/IT_book"<IT_book@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[XiangLinPro/IT_book] 下载之后解压竟然还需要密码，是不是有点恶心人？ (#1)

**Comment by songhao8080** [comment]
是的 有点恶心
