### ISSUE TITLE
链接错误:

### ISSUE THREAD

**Issue by henryhuanghenry** [XiangLinPro/IT_book#2]
TensorFlow 官方文档中文版 百度云下载链接 密码:ni0k 的链接不对

**Comment by XiangLinPro** [comment]
加我微信zijietiaodongpro



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: henryhuanghenry <notifications@github.com&gt;
发送时间: 2020年10月29日 19:07
收件人: XiangLinPro/IT_book <IT_book@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[XiangLinPro/IT_book] 链接错误: (#2)





 
TensorFlow 官方文档中文版 百度云下载链接 密码:ni0k 的链接不对
