### ISSUE TITLE
在开源平台这么干不太合适吧

### ISSUE THREAD

**Issue by Fontzs** [XiangLinPro/IT_book#22]
在b站的评论区看到的，好奇点进来，发现下载的文件都是加密的，瞬间了解到套路了

**Comment by ManulPoly** [comment]
赚的钱可以给他妈买骨灰盒

**Comment by 1024tqs** [comment]
我只想知道怎么才可以不收到关于这个的回复邮件，github上我都取消关注了，这狗娘养的引流🐶。发自我的华为手机-------- 原始邮件 --------发件人： Fontzs ***@***.***>日期： 2021年7月28日周三 06:45收件人： XiangLinPro/IT_book ***@***.***>抄送： Subscribed ***@***.***>主    题： [XiangLinPro/IT_book] 在开源平台这么干不太合适吧 (#22)

在b站的评论区看到的，好奇点进来，发现下载的文件都是加密的，瞬间了解到套路了
