### ISSUE TITLE
关于资料存取的建议

### ISSUE THREAD

**Issue by JIeJaitt** [XiangLinPro/IT_book#29]

**Comment by xiejin520** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wangkaiju** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您发的邮件已收到！

**Comment by liamrhli** [comment]
您的邮件已收到！（本邮件为自动回复信息）

**Comment by xiejin520** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liamrhli** [comment]
您的邮件已收到！（本邮件为自动回复信息）
