### ISSUE TITLE
如果您还有心看到，可否分享到除了百度之外的不卡墙的网盘

### ISSUE THREAD

**Issue by zyppe** [XiangLinPro/IT_book#32]
百度云的限速，您不会不知道吧

**Comment by JietingHuang** [comment]
您的邮件已收到，谢谢！    ——黄杰亭This is an automatic reply, confirming that your email was received.Thank you! ^_^ -- Jieting Huang

**Comment by sky-wdl** [comment]
人家爱分享到哪儿就分享到哪儿，知道怎样不知道又怎么样？他是跟你拿钱了吗？免费无偿分享你还那么多要求

**Comment by liamrhli** [comment]
您的邮件已收到！（本邮件为自动回复信息）

**Comment by xiejin520** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
